local kinds = require("config.icons").kinds

return {
  {
    "echasnovski/mini.icons",
    version = "*",
    opts = {
      lsp = {
        array = { glyph = kinds.Array, hl = "MiniIconsOrange" },
        boolean = { glyph = kinds.Boolean, hl = "MiniIconsOrange" },
        class = { glyph = kinds.Class, hl = "MiniIconsPurple" },
        color = { glyph = kinds.Color, hl = "MiniIconsRed" },
        control = { glyph = kinds.Control, hl = "MiniIconsYellow" },
        constant = { glyph = kinds.Constant, hl = "MiniIconsOrange" },
        constructor = { glyph = kinds.Constructor, hl = "MiniIconsAzure" },
        enum = { glyph = kinds.Enum, hl = "MiniIconsPurple" },
        enummember = { glyph = kinds.EnumMember, hl = "MiniIconsYellow" },
        event = { glyph = kinds.Event, hl = "MiniIconsRed" },
        field = { glyph = kinds.Field, hl = "MiniIconsYellow" },
        file = { glyph = kinds.File, hl = "MiniIconsBlue" },
        folder = { glyph = kinds.Folder, hl = "MiniIconsBlue" },
        ["function"] = { glyph = kinds.Function, hl = "MiniIconsAzure" },
        interface = { glyph = kinds.Interface, hl = "MiniIconsPurple" },
        key = { glyph = kinds.Key, hl = "MiniIconsYellow" },
        keyword = { glyph = kinds.Keyword, hl = "MiniIconsCyan" },
        method = { glyph = kinds.Method, hl = "MiniIconsAzure" },
        module = { glyph = kinds.Module, hl = "MiniIconsPurple" },
        namespace = { glyph = kinds.Namespace, hl = "MiniIconsRed" },
        null = { glyph = kinds.Null, hl = "MiniIconsGrey" },
        number = { glyph = kinds.Number, hl = "MiniIconsOrange" },
        object = { glyph = kinds.Object, hl = "MiniIconsGrey" },
        operator = { glyph = kinds.Operator, hl = "MiniIconsCyan" },
        package = { glyph = kinds.Package, hl = "MiniIconsPurple" },
        property = { glyph = kinds.Property, hl = "MiniIconsYellow" },
        reference = { glyph = kinds.Reference, hl = "MiniIconsCyan" },
        snippet = { glyph = kinds.Snippet, hl = "MiniIconsGreen" },
        string = { glyph = kinds.String, hl = "MiniIconsGreen" },
        struct = { glyph = kinds.Struct, hl = "MiniIconsPurple" },
        text = { glyph = kinds.Text, hl = "MiniIconsGreen" },
        typeparameter = { glyph = kinds.TypeParameter, hl = "MiniIconsCyan" },
        unit = { glyph = kinds.Unit, hl = "MiniIconsCyan" },
        value = { glyph = kinds.Value, hl = "MiniIconsBlue" },
        variable = { glyph = kinds.Variable, hl = "MiniIconsCyan" },
      },
    },
  },
}
